export default [
    {
        name:'Navbar',
        path:'component/common/Navbar/Navbar'
    },
    {
        name:'Header',
        path:'component/common/Header/Header'
    },
    {
        name:'Cards',
        path:'component/common/Card/Cards'
    } ,
    {
        name:'Cards',
        path:'component/common/Card/Cards'
    },
    {
        name:'Button',
        path:'component/common/Button/Button'
    },
    {
        name:'Radio',
        path:'component/common/Radiobtn/Radio'
    },
    {
        name:'Textfield',
        path:'component/common/Textfield/Textfield'
    },
    {
        name:'Hoc',
        path:'component/hoc/Hoc'
    }
]
